### Get Dog Details
GET {{api}}:{{port}}/dev/dogs/1
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response body is correct", function() {

        const data = JSON.parse(response.body);
        client.assert(data.name === "John", "Entity has incorrect name.");
    });

%}



